apiVersion: agones.dev/v1
kind: GameServer
metadata:
  generateName: nodejs-simple-
spec:
  ports:
    - name: default
      portPolicy: Dynamic
      containerPort: 75015
  health:
    # waits for 30 seconds before checking health
    initialDelaySeconds: 30
    # health ping sends every 20 seconds, so let's give it 5 seconds buffer
    periodSeconds: 25
  template:
    spec:
      containers:
        - name: nodejs-simple
          image: cs2server
          resources:
            requests:
              memory: 2Gi
              cpu: 1